"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:52:45.493932+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, max as spark_max, broadcast
from pyspark.sql.types import FloatType, StringType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                       .option("inferSchema", "false")
                       .load(input_path)
                      .withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                      .withColumn("pipeline_run_id", lit(run_id)))

    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                   .option("inferSchema", "false")
                   .load(input_path.replace("transactions.csv", "merchants.csv"))
                   .withColumn("ingestion_timestamp", lit(run_date))
                   .withColumn("source_file", lit("merchants.csv"))
                   .withColumn("pipeline_run_id", lit(run_id)))

    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").parquet(os.path.join(output_path, "transactions", "date={}".format(run_date)))
    merchants_df.write.mode("overwrite").parquet(os.path.join(output_path, "merchants", "date={}".format(run_date)))

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(os.path.join(bronze_path, "transactions", "date={}".format(run_date)))
                       .withColumn("amount", col("amount").cast(FloatType()))
                      .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                      .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                      .withColumn("merchant_id", col("merchant_id").cast(StringType())))

    merchants_df = (spark.read.parquet(os.path.join(merchants_path, "merchants", "date={}".format(run_date)))
                     .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    
    # Cache the merchants dataframe as it is small and referenced multiple times
    merchants_df.cache()

    # Filter NULL transaction_id and negative amounts
    filtered_transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # Deduplicate on transaction_id keeping the latest ingestion_timestamp
    latest_transactions_df = (filtered_transactions_df
                              .groupBy("transaction_id")
                               .agg(spark_max("ingestion_timestamp").alias("max_ingestion_timestamp"))
                              .join(filtered_transactions_df, on=["transaction_id", "ingestion_timestamp"], how="inner"))

    # Join with merchants (broadcast hint)
    enriched_transactions_df = (latest_transactions_df.join(broadcast(merchants_df), on="merchant_id", how="left_outer")
                               .withColumn("quality_flag", 
                                            col("merchant_id").when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED")))

    # Write Silver Parquet partitioned by date
    enriched_transactions_df.write.mode("overwrite").parquet(os.path.join(output_path, "silver", "date={}".format(run_date)))

def main(spark, input_path, merchants_path, output_path, run_date, run_id):
    ingest_bronze(spark, input_path, output_path, run_date, run_id)
    transform_silver(spark, output_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    # Define paths and run metadata
    input_path = "s3://sigma-datatech-raw/transactions/"
    merchants_path = "s3://sigma-datatech-raw/merchants/"
    output_path = "s3://sigma-datatech-analytics/silver/"
    run_date = "2026-05-27"
    run_id = "run_id_12345"

    # Execute the pipeline
    main(spark, input_path, merchants_path, output_path, run_date, run_id)


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, avg, first, last, mode, to_date
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Load Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write Gold layer data
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Load Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum(when(col("status") == "COMPLETED", col("amount"))).alias("total_spent"),
            count("*").alias("total_txns"),
            avg(col("amount")).alias("avg_txn_value"),
            first("transaction_date").alias("first_txn_date"),
            last("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write Gold layer data
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Load Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount"))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(distinct("customer_id")).alias("unique_customers"),
            count(distinct("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write Gold layer data
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for Gold tables
    merchant_performance_output = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output = f"{gold_output_dir}/customer_ltv"
    daily_summary_output = f"{gold_output_dir}/daily_summary"
    
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, merchant_performance_output, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output)
    build_daily_summary(spark, silver_path, daily_summary_output, run_date)
    
    # Write run metadata summary
    run_metadata = {
        "run_date": run_date,
        "merchant_performance_output": merchant_performance_output,
        "customer_ltv_output": customer_ltv_output,
        "daily_summary_output": daily_summary_output
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata.json")

# Initialize Spark session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
