"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:51:13.882534+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, input_file_name, lit, broadcast, when
from pyspark.sql.types import StructType, StructField, StringType, DecimalType, DateType
import uuid

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw transactions as strings
    raw_transactions = spark.read.format("parquet").load(input_path)
    
    # Add metadata columns
    enriched_transactions = raw_transactions.withColumn("ingestion_timestamp", current_timestamp()) \
                                            .withColumn("source_file", input_file_name()) \
                                           .withColumn("pipeline_run_id", lit(str(uuid.uuid4())))
    
    # Partition by ingestion date and write to Bronze layer
    enriched_transactions.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze layer with partition pruning
    bronze_df = spark.read.parquet(bronze_path).where(f"ingestion_timestamp like '{run_date}%'")
    
    # Define schema for casting
    schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("merchant_id", StringType(), True),
        StructField("customer_id", StringType(), True),
        StructField("payment_method", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("transaction_date", StringType(), True),
        StructField("status", StringType(), True),
        StructField("ingestion_timestamp", StringType(), True),
        StructField("source_file", StringType(), True),
        StructField("pipeline_run_id", StringType(), True)
    ])
    
    # Cast columns to correct types
    silver_df = spark.read.schema(schema).option("header", "true").csv(bronze_path)
    silver_df = silver_df.withColumn("amount", col("amount").cast(DecimalType(18,4))) \
                        .withColumn("transaction_date", col("transaction_date").cast(DateType())) \
                       .withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                       .withColumn("merchant_id", col("merchant_id").cast(StringType())) \
                       .withColumn("customer_id", col("customer_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    silver_df = silver_df.filter(col("transaction_id").isNotNull() & col("amount") > 0)
    
    # Keep only transaction_date = run_date - 1
    silver_df = silver_df.filter(col("transaction_date") == f"{run_date}-01")
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    silver_df = silver_df.withColumn("rank", 
                                     when(col("ingestion_timestamp") == silver_df.groupBy("transaction_id").agg({"ingestion_timestamp": "max"}), 1).otherwise(0)) \
                         .filter(col("rank") == 1).drop("rank")
    
    # Read merchants and broadcast it
    merchants_df = spark.read.format("delta").load(merchants_path)
    merchants_df = broadcast(merchants_df)
    
    # Join with merchants
    silver_df = silver_df.join(merchants_df, "merchant_id", "left")
    
    # Add quality_flag column
    silver_df = silver_df.withColumn("quality_flag", 
                                     when(col("transaction_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Check quality halt threshold
    total_rows = silver_df.count()
    bad_rows = silver_df.filter(col("transaction_id").isNull()).count()
    if (bad_rows / total_rows) > 0.05:
        raise Exception("Quality halt threshold exceeded: bad rows > 5%")
    
    # Write to Silver layer
    silver_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("TransactionFeeAnalysis").getOrCreate()
    
    # Define paths and run_date
    input_path = "s3://path/to/transactions_raw"
    bronze_path = "s3://path/to/bronze"
    merchants_path = "s3://path/to/merchants"
    silver_path = "s3://path/to/silver"
    run_date = "2023-10-01"
    run_id = str(uuid.uuid4())
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform to Silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, broadcast, when, sum as _sum, count as _count, max as _max, expr
from pyspark.sql.types import StructType, StructField, StringType, DecimalType, DateType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, gold_output_dir, run_date)
    
    run_metadata = {
        "run_date": run_date,
        "status": "success",
        "tables_written": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    
    spark.read.json(spark.sparkContext.parallelize([run_metadata])).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    silver_df = spark.read.format("delta").load(silver_path)
    
    merchant_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("merchant_id", "merchant_name", "category", "city", "transaction_date") \
       .agg(
            _sum("amount").alias("total_revenue"),
            _count("*").alias("txn_count"),
            _count(when(col("status") == "FAILED", 1)).alias("failed_count")
        ) \
       .withColumn("failure_rate_pct", col("failed_count") / col("txn_count") * 100) \
        .withColumnRenamed("transaction_date", "date")
    
    merchant_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    silver_df = spark.read.format("delta").load(silver_path)
    
    customer_df = silver_df.filter(col("status") == "COMPLETED") \
       .groupBy("customer_id") \
        .agg(
            _sum("amount").alias("total_spent"),
            _count("*").alias("total_txns"),
            _max("transaction_date").alias("last_txn_date"),
            expr("first(transaction_date)").alias("first_txn_date")
        )
    
    # Calculate preferred payment method (mode)
    payment_method_counts = silver_df \
       .groupBy("customer_id", "payment_method") \
       .agg(_count("*").alias("count")) \
        .groupBy("customer_id") \
       .agg(_max("count").alias("max_count"), _max("payment_method").alias("preferred_payment_method"))
    
    customer_df = customer_df.join(payment_method_counts, on="customer_id", how="left") \
        .withColumn("avg_txn_value", col("total_spent") / col("total_txns"))
    
    customer_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    silver_df = spark.read.format("delta").load(silver_path)
    
    daily_summary_df = silver_df.filter(col("transaction_date") == run_date) \
        .groupBy("transaction_date") \
        .agg(
            _sum("amount").alias("total_revenue"),
            _count("*").alias("total_txns"),
            _count(when(col("status") == "COMPLETED", 1)).alias("completed_txns"),
            _count(when(col("status") == "FAILED", 1)).alias("failed_txns"),
            _count(col("customer_id").isNotNull()).alias("unique_customers"),
            _count(col("merchant_id").isNotNull()).alias("unique_merchants")
        ) \
       .withColumn("failure_rate_pct", col("failed_txns") / col("total_txns") * 100) \
       .withColumnRenamed("transaction_date", "date")
    
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

# Gold layer for fee analysis
def build_fee_analysis(spark, silver_path, fee_lookup_path, gold_output_dir, run_date):
    silver_df = spark.read.format("delta").load(silver_df)
    fee_rates_df = spark.read.csv(fee_lookup_path, header=True, inferSchema=True).withColumnRenamed("payment_method", "payment_method").withColumnRenamed("fee_rate", "fee_rate")
    fee_rates_df = broadcast(fee_rates_df)
    
    # Calculate gross revenue and transaction volume by payment method
    gross_revenue_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("payment_method") \
       .agg(_sum("amount").alias("gross_revenue"))
    
    txn_volume_df = silver_df.filter(col("status") == "COMPLETED") \
       .groupBy("payment_method") \
       .agg(_count("*").alias("txn_volume"))
    
    # Join with fee rates and calculate fee amount and effective revenue
    fee_analysis_df = gross_revenue_df.join(fee_rates_df, on="payment_method", how="left") \
       .withColumn("fee_amount", col("gross_revenue") * col("fee_rate")) \
       .withColumn("effective_revenue", col("gross_revenue") * (1 - coalesce(col("fee_rate"), 0)))
    
    # Add analysis date and write to Gold
    fee_analysis_df = fee_analysis_df.withColumn("analysis_date", lit(run_date))
    
    fee_analysis_df.write.partitionBy("analysis_date").mode("overwrite").parquet(f"{gold_output_dir}/fee_analysis")
